feat: enable vcpkg caching in buildpacks
GoogleCloudPlatform/functions-framework-cpp pull request #169
Opened 2021-01-06 04:49 UTC by coryan

2021-01-06 04:50 UTC, coryan commented
/cc: @squee1945 FYI, now with caching for the dependencies.

2021-01-06 16:48 UTC, squee1945 requested changes
I think these hard-coded /layers references need to change?

2021-01-07 04:17 UTC, coryan commented
> I think these hard-coded /layers references need to change?

You are right. The directories are part of the base image though, I will change that in a separate PR, moving them to `/usr/local/` or something similar.

2021-01-07 14:22 UTC, devjgm approved these changes

2021-01-08 03:36 UTC, coryan commented
@squee1945 any thoughts?

2021-01-08 17:28 UTC, squee1945 approved these changes
On the migration to GCP Buildpacks, I suspect we'll want to separate this into multiple buildpacks that can be composed into difference target scenarios (in particular, OSS uber-builder vs. GCF runtime-specific builder).

2021-01-08 17:28 UTC, squee1945 commented on pack/buildpack/bin/build
> +cp -r /layers/cpp/gcf/cmake "${layers}/source"
More `/layers` to convert?

2021-01-08 17:30 UTC, coryan commented on pack/buildpack/bin/build
> +cp -r /layers/cpp/gcf/cmake "${layers}/source"
Yup, thanks.

2021-01-08 17:30 UTC, merged